"""Generate Python 3.14 identifier classes from CPython's Unicode 16 database."""
from pathlib import Path
import sys,unicodedata
assert sys.implementation.name=='cpython' and unicodedata.unidata_version=='16.0.0'
root=Path(__file__).resolve().parents[1]
def ranges(test):
 out=[];start=None
 for cp in range(128,0x110000):
  yes=test(chr(cp))
  if yes and start is None:start=cp
  if not yes and start is not None:out.append((start,cp-1));start=None
 if start is not None:out.append((start,0x10ffff))
 return out
start=ranges(str.isidentifier);cont=ranges(lambda c:('a'+c).isidentifier())
text='// Generated by scripts/gen_python_identifiers.py; CPython Unicode 16.0.0.\n// Sorted inclusive ranges, two six-digit hexadecimal scalars per record.\n'
for name,rs in [('start',start),('continuation',cont)]:
 text+=f'fn {name}_table() -> String = "'+''.join(f'{a:06x}{b:06x}' for a,b in rs)+'"\n'
path=root/'src/identifier_data.almd'
if '--check' in sys.argv:assert path.read_text()==text,'regenerate Unicode tables'
else:path.write_text(text)
print(f'Unicode 16.0.0: {len(start)} start ranges, {len(cont)} continuation ranges')
